pod "MagicalRecord", '~> 2.0.8'
pod 'AFNetworking', '~> 2.5.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'BlurImageProcessor', '~> 1.0.0'
pod 'Reachability', '~> 3.2'
pod 'SwipeView', '~> 1.3.2'
pod 'IQKeyboardManager'
pod 'JSBadgeView', '~> 1.3.2'
pod 'UITextView+Placeholder', '~> 1.0.6'
pod 'SDWebImage', '~> 3.7.1'
pod 'Base64nl', '~> 1.2'
pod 'QBPopupMenu', '~> 2.0'
pod 'UAProgressView', '~> 0.1.1'
pod 'MJRefresh', '~> 1.3.7'
pod 'RNCryptor', '~> 2.2'
